driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: amazon-linux
    driver_config:
      box: mvbcoding/awslinux
  - name: ubuntu-16.04
  - name: ubuntu-14.04
  - name: debian-8.6
  - name: debian-7.11
  - name: centos-7.3
  - name: centos-6.9
  - name: fedora-25
  - name: freebsd-11.0
  - name: freebsd-10.3
  - name: opensuse-leap-42.2
suites:
  - name: openjdk-6
    includes:
      - centos-6.9
      - centos-7.3
      - debian-7.11
      - ubuntu-14.04
      - amazon-linux
    run_list:
      - recipe[test_java::openjdk6]
  - name: openjdk-7
    includes:
      - centos-6.9
      - centos-7.3
      - debian-7.11
      - debian-8.6
      - ubuntu-14.04
      - ubuntu-16.04
      - freebsd-10.3
      - freebsd-11.0
      - opensuse-leap-42.2
      - amazon-linux
    run_list:
      - recipe[test_java::openjdk7]
  - name: openjdk-8
    includes:
      - ubuntu-14.04
      - ubuntu-16.04
      - centos-6.9
      - centos-7.3
      - fedora-25
      - opensuse-leap-42.2
      - amazon-linux
    run_list:
      - recipe[test_java::openjdk8]
  - name: oracle-8
    run_list:
      - recipe[test_java::oracle8]
  - name: oracle-direct
    run_list:
      - recipe[test_java::oracle_direct]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
  - name: openjdk-direct
    run_list:
      - recipe[test_java::openjdk_direct]
  - name: oracle-rpm-8
    includes:
      - centos-6.9
      - centos-7.3
      - fedora-25
    run_list:
      - recipe[test_java::oracle_rpm8]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
