driver:
  name: dokken
  privileged: true # because Docker and SystemD/Upstart
  chef_version: <%= ENV['CHEF_VERSION'] || 'current' %>

transport:
  name: dokken

provisioner:
  name: dokken
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
- name: amazonlinux
  driver:
    image: dokken/amazonlinux
    pid_one_command: /sbin/init

- name: debian-7
  driver:
    image: dokken/debian-7
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-8
  driver:
    image: dokken/debian-8
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: debian-9
  driver:
    image: dokken/debian-9
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: centos-6
  driver:
    image: dokken/centos-6
    pid_one_command: /sbin/init

- name: centos-7
  driver:
    image: dokken/centos-7
    pid_one_command: /usr/lib/systemd/systemd

- name: fedora-latest
  driver:
    image: dokken/fedora-latest
    pid_one_command: /usr/lib/systemd/systemd

- name: ubuntu-14.04
  driver:
    image: dokken/ubuntu-14.04
    pid_one_command: /sbin/init
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: ubuntu-16.04
  driver:
    image: dokken/ubuntu-16.04
    pid_one_command: /bin/systemd
    intermediate_instructions:
      - RUN /usr/bin/apt-get update

- name: opensuse-leap
  driver:
    image: dokken/opensuse-leap
    pid_one_command: /bin/systemd
    

suites:
  - name: openjdk-6
    includes:
      - centos-6
      - centos-7
      - debian-7
      - ubuntu-14.04
      - amazonlinux
    run_list:
      - recipe[test_java::openjdk6]
  - name: openjdk-7
    includes:
      - centos-6
      - centos-7
      - debian-7
      - debian-8
      - ubuntu-14.04
      - ubuntu-16.04
      - opensuse-leap
      - amazonlinux
    run_list:
      - recipe[test_java::openjdk7]
  - name: openjdk-8
    includes:
      - ubuntu-14.04
      - ubuntu-16.04
      - centos-6
      - centos-7
      - fedora-latest
      - opensuse-leap
      - amazon-linux
    run_list:
      - recipe[test_java::openjdk8]
  - name: oracle-8
    run_list:
      - recipe[test_java::oracle8]
  - name: oracle-direct
    run_list:
      - recipe[test_java::oracle_direct]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
  - name: openjdk-direct
    run_list:
      - recipe[test_java::openjdk_direct]
  - name: oracle-rpm-8
    includes:
      - centos-6
      - centos-7
      - fedora-latest
    run_list:
      - recipe[test_java::oracle_rpm8]
    verifier:
      inspec_tests:
        - test/integration/oracle-8
