Lint/UselessAssignment:
  Exclude:
    - 'resources/oracle_install.rb'

Style/AccessorMethodName:
  Exclude:
    - 'libraries/matchers.rb'

Style/FormatString:
  Exclude:
    - 'libraries/helpers.rb'
